package rabbitmq

import (
	"time"

	amqp "github.com/rabbitmq/amqp091-go"
)

// ClientConfig represents the configuration of a client instance.
type ClientConfig struct {
	ConnectionConfig ConnectionConfig
	ChannelConfig    ChannelConfig
}

// ConnectionConfig contains all the configurable parameters used by a client instance
// to connect to a RabbitMQ server.
type ConnectionConfig struct {
	URL         string
	Username    string
	Password    string
	Host        string
	Port        string
	VirtualHost string
	RetryDelay  time.Duration
	Timeout     time.Duration
}

const (
	// DefaultConnectionTimeout is the default duration the client will wait until a successful connection.
	DefaultConnectionTimeout = time.Minute * 1
	// DefaultConnectionRetryDelay is the default delay between each connection attempt.
	DefaultConnectionRetryDelay = time.Second * 5
)

// DefaultConnectionConfig is the default configuration used by the client to connect
// to the server.
var DefaultConnectionConfig = ConnectionConfig{
	Username:    "guest",
	Password:    "guest",
	Host:        "localhost",
	Port:        "5672",
	VirtualHost: "",
	RetryDelay:  DefaultConnectionRetryDelay,
	Timeout:     DefaultConnectionTimeout,
}

// ChannelConfig contains all the configurable parameters used by a client instance
// to initialize a RabbitMQ channel.
type ChannelConfig struct {
	PrefetchCount            int
	PrefetchSize             int
	IsGlobal                 bool
	InitializationRetryDelay time.Duration
}

const (
	// DefaultPrefetchCount is the default number of messages the server will be able to send to your consumer
	// before receiving acknowledgment.
	DefaultPrefetchCount = 1
	// DefaultChannelInitializationRetryDelay is the default delay between each channel initialization attempt.
	DefaultChannelInitializationRetryDelay = time.Second * 5
)

// DefaultChannel is the default configuration used by a client to initialize
// a RabbitMQ channel.
var DefaultChannelConfig = ChannelConfig{
	PrefetchCount:            DefaultPrefetchCount,
	PrefetchSize:             0,
	IsGlobal:                 false,
	InitializationRetryDelay: DefaultChannelInitializationRetryDelay,
}

// PublishConfig contains all the configurable parameters used by a client instance
// to publish messages.
type PublishConfig struct {
	ExchangeName   string
	RoutingKey     string
	IsMandatory    bool
	IsImmediate    bool
	TTL            string // TTL is applied on a message-by-message basis and is represented in millisecond.
	MessageHeaders amqp.Table
	RetryDelay     time.Duration
	Timeout        time.Duration
}

const (
	// DefaultPublishRetryDelay is the default delay between each attempt to publish
	// a RabbitMQ message.
	DefaultPublishRetryDelay = time.Second * 5
	// DefaultPublishTimeout is the default duration the client will wait until the server
	// confirms to the client the message a successfully been published.
	DefaultPublishTimeout = time.Second * 20
)

// DefaultPublishConfig is the default configuration used by a client instance to publish messages.
var DefaultPublishConfig = PublishConfig{
	ExchangeName:   "", // Default exchange
	RoutingKey:     "",
	IsMandatory:    false,
	IsImmediate:    false,
	TTL:            "",
	MessageHeaders: nil,
	RetryDelay:     DefaultPublishRetryDelay,
	Timeout:        DefaultPublishTimeout,
}

// ConsumerConfig contains all the configurable parameters used by a client instance
// to consume messages.
type ConsumerConfig struct {
	QueueName                string
	Name                     string
	AutoAck                  bool
	IsExclusive              bool
	IsNoWait                 bool
	IsNoLocal                bool
	InitializationRetryDelay time.Duration
	Arguments                amqp.Table
}

const (
	// DefaultConsumerInitializationRetryDelay is the delay between each consumer initialization attempt.
	DefaultConsumerInitializationRetryDelay = time.Second * 5
)

// DefaultConsumerConfig is the default configuration used by a client instance to consume messages.
var DefaultConsumerConfig = ConsumerConfig{
	Name:                     "", // Automatically generated by RabbitMQ
	QueueName:                "",
	AutoAck:                  false,
	IsExclusive:              false,
	IsNoWait:                 false,
	IsNoLocal:                false,
	InitializationRetryDelay: DefaultConsumerInitializationRetryDelay,
	Arguments:                nil,
}

// ExchangeType defines the functionality of the exchange i.e. how messages are routed through it.
type ExchangeType string

func (t ExchangeType) String() string {
	return string(t)
}

const (
	// https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-direct
	DirectExchangeType ExchangeType = "direct"
	// https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-fanout
	FanoutExchangeType ExchangeType = "fanout"
	// https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-topic
	TopicExchangeType ExchangeType = "topic"
	// https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-headers
	HeadersExchangeType ExchangeType = "headers"
	// https://github.com/rabbitmq/rabbitmq-delayed-message-exchange
	DelayedMessageExchangeType ExchangeType = "x-delayed-message"
)

const (
	// DelayedTypeArgument is the key used to specify the exchange type of a
	// delayed message exchange.
	//
	// https://github.com/rabbitmq/rabbitmq-delayed-message-exchange
	DelayedTypeArgument = "x-delayed-type"
)

const (
	// DelayMessageHeader is the key used to specify the delay before publishing
	// the message to the queue.
	//
	// https://github.com/rabbitmq/rabbitmq-delayed-message-exchange
	DelayMessageHeader = "x-delay"
)

// ExchangeConfig contains all the configurable parameters used by a client instance
// to declare an exchange.
type ExchangeConfig struct {
	Name         string
	Type         ExchangeType
	IsDurable    bool
	IsAutoDelete bool
	IsInternal   bool
	IsNoWait     bool
	Arguments    amqp.Table
}

// DefaultExchangeConfig is the default configuration used by a client instance to declare exchanges.
var DefaultExchangeConfig = ExchangeConfig{
	Name:         "", // Default exchange
	Type:         DirectExchangeType,
	IsDurable:    true,
	IsAutoDelete: false,
	IsInternal:   false,
	IsNoWait:     false,
}

// ConsumerConfig contains all the configurable parameters used by a client instance to declare a
// queue.
type QueueConfig struct {
	Name                string
	QueueBindRoutingKey string
	IsDurable           bool
	IsExclusive         bool
	AutoDelete          bool
	NoWait              bool
	Arguments           amqp.Table
}

// DefaultConsumerConfig is the default configuration used by a client instance to declare queues.
var DefaultQueueConfig = QueueConfig{
	Name:                "", // Automatically generated by RabbitMQ
	QueueBindRoutingKey: "",
	IsDurable:           true,
	IsExclusive:         false,
	AutoDelete:          false,
	NoWait:              false,
	Arguments:           nil,
}

const (
	// DeadLetterExchangeNameArgument is the key used in the queue optionnal arguments
	// to specify the name of the dead letter exchange of a queue through its optionnal arguments.
	DeadLetterExchangeNameArgument = "x-dead-letter-exchange"
	// DeadLetterRoutingKeyArguement is the key used in the queue optionnal arguments
	// to specify the routing key of the message sent to the dead letter exchange.
	DeadLetterRoutingKeyArgument = "x-dead-letter-routing-key"
	// QueueTypeArgument is the key used in the queue optionnal arguments to specify
	// the queue type.
	QueueTypeArgument = "x-queue-type"
)

const (
	// QuorumQueueType is the value used with the key "x-queue-type" in the optionnal
	// arguments when declaring a queue to declare a Quorum queue.
	QuorumQueueType = "quorum"
)
